apiVersion: v2
name: scylla-operator
description: Scylla Operator is a Kubernetes Operator for managing and automating tasks related to managing a Scylla clusters.
version: 0.0.0 # overwritten during publishing
appVersion: "1.9" # overwritten during publishing
keywords:
  - scylla
  - scylladb
  - scylla-operator
  - operator
home: https://www.scylladb.com/
sources:
  - https://github.com/scylladb/scylla-operator
maintainers:
  - name: Maciej Zimnoch
    email: maciej@scylladb.com
icon: https://github.com/scylladb/scylla-operator/raw/master/logo.png
