apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: scylladb-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ScyllaDB Operator
  image: "" # Replaced in CI
  publisher: ScyllaDB
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m
