apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: scylladb-operator-subscription
  namespace: scylla-operator
spec:
  channel: "" # Replaced in CI.
  installPlanApproval: Automatic
  name: scylladb-operator
  source: scylladb-operator-catalog
  sourceNamespace: openshift-marketplace
