apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: scylla-manager-controller
  namespace: scylla-manager
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scylla-manager-controller
