apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: clusters.scylla.scylladb.com
spec:
  group: scylla.scylladb.com
  names:
    kind: Cluster
    plural: clusters
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            agentRepository:
              description: Repository to pull the agent image from. Defaults to "scylladb/scylla-manager-agent".
              type: string
            agentVersion:
              description: Version of Scylla Manager Agent to use. Defaults to "latest".
              type: string
            alternator:
              description: Alternator designates this cluster an Alternator cluster
              properties:
                port:
                  description: Port on which to bind the Alternator API
                  format: int32
                  type: integer
              type: object
            cpuset:
              description: CpuSet determines if the cluster will use cpu-pinning for
                max performance.
              type: boolean
            datacenter:
              description: Datacenter that will make up this cluster.
              properties:
                name:
                  description: Name of the Scylla Datacenter. Used in the cassandra-rackdc.properties
                    file.
                  type: string
                racks:
                  description: Racks of the specific Datacenter.
                  items:
                    properties:
                      members:
                        description: Members is the number of Scylla instances in
                          this rack.
                        format: int32
                        type: integer
                      name:
                        description: Name of the Scylla Rack. Used in the cassandra-rackdc.properties
                          file.
                        type: string
                      placement:
                        description: Placement describes restrictions for the nodes
                          Scylla is scheduled on.
                        properties:
                          tolerations:
                            items:
                              type: object
                            type: array
                        type: object
                      resources:
                        description: Resources the Scylla Pods will use.
                        type: object
                      scyllaAgentConfig:
                        description: Scylla config map name to customize scylla manager
                          agent
                        type: string
                      scyllaConfig:
                        description: Scylla config map name to customize scylla.yaml
                        type: string
                      storage:
                        description: Storage describes the underlying storage that
                          Scylla will consume.
                        properties:
                          capacity:
                            description: Capacity of each member's volume
                            type: string
                          storageClassName:
                            description: Name of storageClass to request
                            type: string
                        required:
                        - capacity
                        type: object
                    required:
                    - name
                    - members
                    - storage
                    - resources
                    - scyllaConfig
                    - scyllaAgentConfig
                    type: object
                  type: array
              required:
              - name
              - racks
              type: object
            developerMode:
              description: DeveloperMode determines if the cluster runs in developer-mode.
              type: boolean
            repository:
              description: Repository to pull the image from.
              type: string
            sidecarImage:
              description: User-provided image for the sidecar that replaces default.
              properties:
                repository:
                  description: Repository to pull the image from.
                  type: string
                version:
                  description: Version of the image.
                  type: string
              required:
              - version
              - repository
              type: object
            version:
              description: Version of Scylla to use.
              type: string
          required:
          - version
          - agentVersion
          - datacenter
          type: object
        status:
          properties:
            racks:
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
