# Role for scylla members.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-member
  namespace: scylla-manager-system
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - "apps"
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - scylla.scylladb.com
    resources:
      - clusters
    verbs:
      - get

---

# ServiceAccount for scylla members.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-member
  namespace: scylla-manager-system

---
# RoleBinding for scylla members.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: member-rolebinding
  namespace: scylla-manager-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-member
subjects:
  - kind: ServiceAccount
    name: scylla-manager-cluster-member
    namespace: scylla-manager-system

---
# Scylla Manager Cluster
apiVersion: scylla.scylladb.com/v1alpha1
kind: Cluster
metadata:
  name: cluster
  namespace: scylla-manager
spec:
  version: 4.2.0
  agentVersion: 2.2.0
  developerMode: true
  datacenter:
    name: manager-dc
    racks:
      - name: manager-rack
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 1
        storage:
          capacity: 5Gi
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
