apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: scylla-operator-webhook
  labels:
    app.kubernetes.io/name: webhook-server
    app.kubernetes.io/instance: webhook-server
spec:
  ports:
  - port: 443
    targetPort: 5000
    name: webhook
  selector:
    app.kubernetes.io/name: webhook-server
    app.kubernetes.io/instance: webhook-server
