{{- if gt .Values.webhookServerReplicas 1.0 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: webhook-server
  namespace: scylla-operator
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook-server
      app.kubernetes.io/instance: webhook-server
{{- end }}
