---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.3
  creationTimestamp: null
  name: scyllaoperatorconfigs.scylla.scylladb.com
spec:
  group: scylla.scylladb.com
  names:
    kind: ScyllaOperatorConfig
    listKind: ScyllaOperatorConfigList
    plural: scyllaoperatorconfigs
    singular: scyllaoperatorconfig
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .metadata.creationTimestamp
          name: AGE
          type: date
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: ScyllaOperatorConfig describes the Scylla Operator configuration.
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: spec defines the desired state of the operator.
              properties:
                scyllaUtilsImage:
                  description: scyllaUtilsImage is a ScyllaDB image used for running ScyllaDB utilities.
                  type: string
                unsupportedBashToolsImageOverride:
                  description: unsupportedBashToolsImageOverride allows to adjust a generic Bash image with extra tools used by the operator for auxiliary purposes. Setting this field renders your cluster unsupported. Use at your own risk.
                  type: string
                unsupportedGrafanaImageOverride:
                  description: unsupportedGrafanaImageOverride allows to adjust Grafana image used by the operator for testing, dev or emergencies. Setting this field renders your cluster unsupported. Use at your own risk.
                  type: string
                unsupportedPrometheusVersionOverride:
                  description: unsupportedPrometheusVersionOverride allows to adjust Prometheus version used by the operator for testing, dev or emergencies. Setting this field renders your cluster unsupported. Use at your own risk.
                  type: string
              type: object
            status:
              description: status defines the observed state of the operator.
              properties:
                bashToolsImage:
                  description: bashToolsImage is a generic Bash image with extra tools used by the operator for auxiliary purposes.
                  type: string
                grafanaImage:
                  description: grafanaImage is the image used by the operator to create a Grafana instance.
                  type: string
                observedGeneration:
                  description: observedGeneration is the most recent generation observed for this ScyllaOperatorConfig. It corresponds to the ScyllaOperatorConfig's generation, which is updated on mutation by the API Server.
                  format: int64
                  type: integer
                prometheusVersion:
                  description: prometheusVersion is the Prometheus version used by the operator to create a Prometheus instance.
                  type: string
                scyllaDBUtilsImage:
                  description: scyllaDBUtilsImage is the ScyllaDB image used for running ScyllaDB utilities.
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
