apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scylladb:controller:operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scylladb:controller:operator
subjects:
- kind: ServiceAccount
  name: scylla-operator
  namespace: scylla-operator
