apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scylla-operator-selfsigned
  namespace: scylla-operator
spec:
  dnsNames:
  - scylla-operator-webhook.scylla-operator.svc
  - scylla-operator-webhook.scylla-operator.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: scylla-operator-selfsigned-issuer
  secretName: scylla-operator-serving-cert
