# Scylla Cluster
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: {{ include "scylla.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  version: {{ .Values.scyllaImage.tag }}
  repository: {{ .Values.scyllaImage.repository }}
  agentVersion: {{ .Values.agentImage.tag }}
  agentRepository: {{ .Values.agentImage.repository }}
  {{- if .Values.alternator.enabled }}
  alternator:
    port: {{ .Values.alternator.port }}
    writeIsolation: {{ .Values.alternator.writeIsolation }}
  {{- end }}
  developerMode: {{ .Values.developerMode }}
  cpuset: {{ .Values.cpuset }}
  automaticOrphanedNodeCleanup: {{ .Values.automaticOrphanedNodeCleanup }}
  {{- with .Values.sysctls }}
  sysctls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  network:
    hostNetworking: {{ .Values.hostNetworking }}
  {{- with .Values.backups }}
  backups:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.repairs }}
  repairs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  datacenter:
    name: {{ .Values.datacenter }}
    racks:
      {{- range .Values.racks }}
      - name: {{ .name }}
        scyllaConfig: {{ default "scylla-config" .scyllaConfig }}
        scyllaAgentConfig: {{ default "scylla-agent-config" .scyllaAgentConfig }}
        members: {{ .members }}
        storage:
          storageClassName: {{ .storage.storageClassName }}
          capacity: {{ .storage.capacity }}
        resources:
          {{- toYaml .resources | nindent 10 }}
        {{- if .agentResources }}
        agentResources:
          {{- toYaml .agentResources | nindent 10 }}
        {{- end }}
        {{- if .volumes }}
        volumes:
          {{- toYaml .volumes | nindent 10 }}
        {{- end }}
        {{- if .volumeMounts }}
        volumeMounts:
          {{- toYaml .volumeMounts | nindent 10 }}
        {{- end }}
        {{- if .agentVolumeMounts }}
        agentVolumeMounts:
          {{- toYaml .agentVolumeMounts | nindent 10 }}
        {{- end }}
        {{- if .placement }}
        placement:
          {{- if .placement.podAffinity }}
          podAffinity:
            {{- toYaml .placement.podAffinity | nindent 12 }}
          {{- end }}
          {{- if .placement.podAntiAffinity }}
          podAntiAffinity:
            {{- toYaml .placement.podAntiAffinity | nindent 12 }}
          {{- end }}
          {{- if .placement.nodeAffinity }}
          nodeAffinity:
            {{- toYaml .placement.nodeAffinity | nindent 12 }}
          {{- end }}
          {{- if .placement.tolerations }}
          tolerations:
            {{- toYaml .placement.tolerations | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
