[tool.poetry]
name = "scylla-operator-docs"
description = "Scylla Operator Documentation"
version = "0.0.1"
authors = ["ScyllaDB Documentation Contributors"]

# Pin dependencies to exact versions so CI always produces the same artifacts.
[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "^5.4"
pygments = "^2.9"
recommonmark = "0.5.0"
sphinx-scylladb-theme = "^1.0.0"
sphinx-sitemap = "2.1.0"
sphinx-autobuild = "0.7.1"
Sphinx = "2.4.4"
sphinx-multiversion-scylla = "~0.2.6"
sphinx-markdown-tables = "0.0.15"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
